travis:
  secure:
    BINSTAR_TOKEN: 6zacNfDy33znLeFOp+JtFt15Qd5rGAkTIaCBeV5f4QM9SDGA0LyLzUjj0fPMNHjMnpFAxTcy2QlcUtXV6A85SofCl8hpUkIM1AlA0cd7zUgJ/HTPHAVxwNtnPPR+Ov3h5tommQulliAHKFaTOsavbxNzoPnoIAfo2K7CKfqvCWT7IO2pBfHT0tguTaTvIG4gN4RExS0i0cmoEtIWX23t4DIecYKsEayVXg0/XWPNa9TqFEC+TRzgXwumebpxQwPPiiFOUxCgM3GPakEQLOUnmSET5vCy+NA5wRGRzg3JR+eEeSpxfiCDGpMxPkjXp7SZzjQZqMniuFUFLoYLn9vWnRfMRn3gwONWJaf7Z0vXu+4DbwyEpCWdunurKxLzE+N77YJAQMMsS0le6pw5OkiLSKgsUgmYQF3PdHkuAMaqU6zI93Gk6ScLaeqezy/A/3e2XBe6lPRVNlUQk+AC+YsAN8PW6vSC4Jp0OmWLitgWdxLmToOuIDYkT3sEBk/sOKEy7MRh4vkR7zbxBm+ABECF2mebef6IwJYDwjJLsI/FNUdpISGw1LYbnj5nRi/kKq94R1pFrgkQc8wE/imXa9b5kwVja8SbYhpyN0UP8uURJYn1SenV43HeELMaTgWT/X1tEXSIdxak+QtriPN+y8a6xzvmq6JO/zNcjovIrsS3OKQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
